image: "rust:latest"

build:cargo:
  script:
    - rustc --version && cargo --version  # Print version info
    - cargo build --verbose --release --package platform_linux

test:cargo:
  script:
    - rustc --version && cargo --version  # Print version info
    - cargo test --verbose --release --no-default-features --no-fail-fast --package platform_linux
