image: "rust:latest"

pipelines:
  default:
    - parallel:
        - step:
            name: build
            script:
              - rustc --version && cargo --version # Print version information
              - cargo build --verbose --release --package platform_linux

        - step:
            name: test
            script:
              - rustc --version && cargo --version # Print version info
              - cargo test --verbose --release --no-default-features --no-fail-fast --package platform_linux
