pipeline {
    agent {
        // If you need a special Jenkins Agent to run docker, specify the label **here and below**
        label 'docker'
    }
    options {
        // Disables concurrent builds
        // I.e. only one build at a time
        disableConcurrentBuilds()
    }
    stages {
        stage('Rust Versions') {
            agent {
                docker { 
                    // Which image to use
                    image 'rust:latest' 
                    // Reuse the same node, avoids having to clone the repository on all nodes
                    reuseNode true
                }
            }
            steps {
                // Print out versions
                sh 'rustc --version'
                sh 'cargo --version'
                sh 'rustup --version'
            }
        }
        stage('Rust Check') {
            agent {
                docker { 
                    // Which image to use
                    image 'rust:latest' 
                    // Reuse the same node, avoids having to clone the repository on all nodes
                    reuseNode true
                }
            }
            steps {
                // Run a check
                sh 'cargo check'
            }
        }
        stage('Rust Build (Debug)') {
            agent {
                docker { 
                    // Which image to use
                    image 'rust:latest' 
                    // Reuse the same node, avoids having to clone the repository on all nodes
                    reuseNode true
                }
            }
            steps {
                // Debug Build
                sh 'cargo build'
            }
        }
        stage('Rust Build (Release)') {
            agent {
                docker { 
                    image 'rust:latest' 
                    reuseNode true
                }
            }
            steps {
                // Release build
                sh 'cargo build --release'
            }
        }
        stage('Rust Test (Debug)') {
            agent {
                docker { 
                    // Which image to use
                    image 'rust:latest' 
                    // Reuse the same node, avoids having to clone the repository on all nodes
                    reuseNode true
                }
            }
            steps {
                // Debug Test
                sh 'cargo test --no-default-features'
            }
        }
        stage('Rust Test (Release)') {
            agent {
                docker { 
                    image 'rust:latest' 
                    reuseNode true
                }
            }
            steps {
                // Release Test
                sh 'cargo test --no-default-features --release'
            }
        }
    }
}