name: Platform Windows

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  platform_windows:
    strategy:
      matrix:
        os: [windows-latest]
        target: [x86_64-pc-windows-msvc]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Cache target/
        id: target-cache
        uses: actions/cache@v3
        with:
          path: target
          key: platform_windows-${{ runner.os }}-${{ matrix.target }}-target

      - name: Install Rust
        run: Invoke-WebRequest https://static.rust-lang.org/rustup/dist/x86_64-pc-windows-msvc/rustup-init.exe -OutFile rustup-init.exe; ./rustup-init.exe --default-toolchain stable --profile minimal -y

      - name: Install target ${{ matrix.target }}
        run: rustup target add ${{ matrix.target }}

      - name: Check
        run: cargo check --verbose --package platform_windows --target ${{ matrix.target }}
      - name: Build (Debug)
        run: cargo build --verbose --package platform_windows --target ${{ matrix.target }}
      - name: Build (Release)
        run: cargo build --verbose --package platform_windows --target ${{ matrix.target }} --release
      - name: Run Tests (Debug)
        if: ${{ matrix.target == 'x86_64-pc-windows-msvc' }} # Testing can only be done on the host architecture. It should work across all architectures though!
        run: cargo test --verbose --package platform_windows --no-default-features --no-fail-fast --target ${{ matrix.target }}
        continue-on-error: true
      - name: Run Tests (Release)
        if: ${{ matrix.target == 'x86_64-pc-windows-msvc' }} # Testing can only be done on the host architecture. It should work across all architectures though!
        run: cargo test --verbose --package platform_windows --no-default-features --no-fail-fast --target ${{ matrix.target }} --release
        continue-on-error: true

      - uses: actions/upload-artifact@v3
        with:
          name: "platform_windows_debug_${{ matrix.target }}"
          path: target/${{ matrix.target }}/debug/platform_windows.exe
          if-no-files-found: error
      - uses: actions/upload-artifact@v3
        with:
          name: "platform_windows_release_${{ matrix.target }}"
          path: target/${{ matrix.target }}/release/platform_windows.exe
          if-no-files-found: error
