name: Platform iOS

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  platform_ios:
    strategy:
      matrix:
        os: [macos-latest]
        # No target needed here.
        # xcodebuild automatically builds for all architectures and compresses them into one APP
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Cache target/
        id: target-cache
        uses: actions/cache@v3
        with:
          path: target
          key: platform_ios-${{ runner.os }}-target

      - name: Install Rust
        run: curl https://sh.rustup.rs -sSf | sh -s -- --default-toolchain stable --profile minimal -y

      - name: Install target x86_64-apple-ios
        run: rustup target add x86_64-apple-ios
      - name: Install target aarch64-apple-ios
        run: rustup target add aarch64-apple-ios
      - name: Install target aarch64-apple-ios-sim
        run: rustup target add aarch64-apple-ios-sim

      - name: Install cargo-xcodebuild
        run: cargo install cargo-xcodebuild

      - name: Install XCodeGen
        run: brew install xcodegen
      - name: Install JQ
        run: brew install jq

      - name: Make a copy of original Cargo.toml
        run: cp platform/ios/Cargo.toml platform/ios/Cargo.toml.original
      - name: Available Device IDs
        run: xcrun simctl list devices available --json ios | jq '.devices | to_entries | map(select(.key | match(".*iOS.*"))) | map(.value)[0]'
      - name: Selected Device ID
        run: xcrun simctl list devices available --json ios | jq '.devices | to_entries | map(select(.key | match(".*iOS.*"))) | map(.value)[0][0]'
      - name: Change Device ID
        run: DEVICE_ID=$(xcrun simctl list devices available --json ios | jq '.devices | to_entries | map(select(.key | match(".*iOS.*"))) | map(.value)[0][0].udid'); cat platform/ios/Cargo.toml | sed "s/device_id = .*/device_id = $DEVICE_ID/g" | tee platform/ios/Cargo.toml
      - name: Diff changes in Cargo.toml
        run: diff platform/ios/Cargo.toml platform/ios/Cargo.toml.original || true

      - name: Check
        run: cargo xcodebuild check --verbose --package platform_ios
      - name: Build (Debug)
        run: cargo xcodebuild build --verbose --package platform_ios
      - name: Build (Release)
        run: cargo xcodebuild build --verbose --package platform_ios --release
      # Testing can't be done on iOS.
      # However, we are testing on the `shared` code and other architectures.

      - uses: actions/upload-artifact@v3
        with:
          name: "platform_ios_debug_multi"
          path: target/xcodegen/platform_ios/build/Build/Products/Debug-iphonesimulator
          if-no-files-found: error
      - uses: actions/upload-artifact@v3
        with:
          name: "platform_ios_release_multi"
          path: target/xcodegen/platform_ios/build/Build/Products/Release-iphonesimulator
          if-no-files-found: error
